# Generated by Django 5.0.3 on 2024-05-10 18:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stockmgmt", "0002_stockhistory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockhistory",
            name="last_update",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="stockhistory",
            name="timestamp",
            field=models.DateTimeField(null=True),
        ),
    ]
